/**
 * @file Config.h
 * @brief AUTO-GENERATED FILE from project_config.json. DO NOT EDIT MANUALLY.
 * @date Generated by Tools/generate_config.py
 */

#pragma once

namespace Config {

    namespace Plant {
        constexpr float MASS_KG = 0.016;
        constexpr float GRAVITY = 9.81;
        constexpr float EQUILIBRIUM_DIST_M = 0.03;
        constexpr float COIL_RESISTANCE = 15.0;
        constexpr float COIL_INDUCTANCE = 0.01;
    }

    namespace Control {
        constexpr float LOOP_FREQ_HZ = 5000;
        constexpr float LOOP_PERIOD_S = 1.0f / 5000;
        constexpr float TARGET_DIST_M = 0.02;
        
        namespace PID {
            constexpr float KP = 1000.0;
            constexpr float KI = 50.0;
            constexpr float KD = 25.0;
        }
    }

    namespace Hardware {
        constexpr int PIN_HALL = 34;
        constexpr int PIN_PWM = 25;
        
        constexpr int ADC_BITS = 12;
        constexpr float ADC_REF_V = 3.3;
        constexpr float HALL_OFFSET_V = 2.5;
        
        constexpr int PWM_FREQ = 20000;
        constexpr int PWM_BITS = 10;
    }
}
