/**
 * @file AutoTuning.cpp
 * @brief Ziegler-Nichols Kp Search Lab (WITH COIL COMPENSATION)
 * 
 * This version compensates for the magnetic field generated by the coil itself,
 * preventing the sensor from being "fooled" by the actuator's own field.
 */

#include <Arduino.h>
#include "Config.h"
#include "Aether_HAL.h"
#include "PID_Controller.h"
#include "MovingAverage.h"

// Objects
Aether_HAL hal;
PID_Controller pid(0.0, 0.0, 0.0, Config::Control::LOOP_PERIOD_S);
MovingAverage filter;

// Tuning Variables
bool tuningActive = false;
float testKp = 0.0f;
unsigned long lastStepTime = 0;
const int STEP_DELAY_MS = 500;       // How often to increase Kp
const float KP_INCREMENT = 0.0001f;  // Kp increment step
const float GRAPH_SCALE = 100000.0f; // Scaling for visualization in Serial Plotter

// Variable to store the previous PWM output (for compensation logic)
float last_pwm_output = 0.0f;

void setup() {
    Serial.begin(115200);
    hal.init();
    hal.setCoilPower(0.0f);
    filter.begin(Config::Control::FILTER_SIZE);
    delay(1000);
    
    Serial.println("--- PID AUTO-TUNING (COMPENSATED) ---");
    Serial.println("The sensor reading will be corrected using the coupling factor.");
    Serial.println("[a] -> START Tuning");
    Serial.println("[s] -> STOP / Emergency Reset");
}

void loop() {
    // 1. Hardware Reading
    int raw = hal.readSensorRaw();
    float filtered = filter.process((float)raw);
    
    // --- 2. COMPENSATION ---
    // We use the coupling factor (calculated via R/MATLAB or testing) found in Config.h
    // If the coil's field decreases the sensor value, we add it back.
    float coil_interference = last_pwm_output * Config::Hardware::HALL_COIL_COUPLING;
    float corrected_val = filtered + coil_interference; 

    float target = Config::Control::TARGET_ADC;
    float currentOutput = 0.0f;

    // Serial Command Handling
    if (Serial.available() > 0) {
        char cmd = Serial.read();
        while(Serial.available()) Serial.read(); // Clear buffer

        if (cmd == 's') {
            tuningActive = false;
            testKp = 0.0f;
            pid.setKp(0.0f);
            hal.setCoilPower(0.0f);
            Serial.println("\n>>> TUNING STOPPED.");
        }
        else if (cmd == 'a') {
            tuningActive = true;
            testKp = 0.0f;
            pid.setKp(0.0f); pid.setKi(0.0f); pid.setKd(0.0f);
            Serial.println("\n>>> TUNING STARTED.");
        }
    }

    // Auto-Tuning Logic
    if (tuningActive) {
        // Increment Kp over time
        if (millis() - lastStepTime > STEP_DELAY_MS) {
            lastStepTime = millis();
            testKp += KP_INCREMENT;
            pid.setKp(testKp);
        }

        // The PID now processes the CORRECTED value, not the raw/noisy one
        currentOutput = pid.compute(target, corrected_val);
        
        // Safety Clamp (0.0 to 1.0)
        if(currentOutput > 1.0f) currentOutput = 1.0f;
        if(currentOutput < 0.0f) currentOutput = 0.0f;

        hal.setCoilPower(currentOutput);
        hal.setWarningLed(true); 
    } else {
        hal.setCoilPower(0.0f);
        hal.setWarningLed(false);
        currentOutput = 0.0f;
    }
    
    // Save current output to be used for compensation in the NEXT loop cycle
    last_pwm_output = currentOutput;

    // Telemetry (Optimized for Serial Plotter)
    static unsigned long lastPrint = 0;
    if (millis() - lastPrint > 50) {
        lastPrint = millis();
        // Compare Filtered (Raw) vs Corrected to see the effect of compensation
        Serial.print(">Filtered_Raw:"); Serial.print((int)filtered);
        Serial.print(",Corrected:");    Serial.print((int)corrected_val);
        Serial.print(",Target:");       Serial.print((int)target);
        Serial.print(",Kp_scaled:");    Serial.print(testKp * GRAPH_SCALE); 
        Serial.print(",PWM_Percent:");  Serial.println(currentOutput * 100.0f);
    }
}