"""
@file generate_config.py
@brief Configuration Propagation Tool (SSOT Implementation).
@details This script acts as the bridge between the single source of truth (project_config.json)
         and the specific environments (Firmware, Simulation, Documentation).
         It reads the master JSON and auto-generates:
         1. C++ Header (Config.h) for the ESP32 Firmware (compile-time constants).
         2. MATLAB Script (load_params.m) for Simulink models.
         3. Markdown Table (System_Parameters.md) for project documentation.
         
@author Michele Bisignano
@project Aether-Lock
"""

import json
import os

# --- PATH CONFIGURATION ---   
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__)) # get the current script's directory
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR) # Aether-Lock root directory

JSON_PATH = os.path.join(PROJECT_ROOT, "project_config.json") 
CPP_PATH = os.path.join(PROJECT_ROOT, "Firmware", "include", "Config.h")
MATLAB_PATH = os.path.join(PROJECT_ROOT, "Simulation", "MATLAB", "load_params.m")
DOCS_PATH = os.path.join(PROJECT_ROOT, "Docs", "Theory", "System_Parameters.md")

def load_config():
    print(f"Reading configuration from: {JSON_PATH}")
    with open(JSON_PATH, 'r') as f:
        return json.load(f)
    
    
def generate_cpp_header(data):
    print(f"Generating C++ Header: {CPP_PATH}")
    
    phy = data["physical_plant"]
    ctrl = data["control_system"]
    hw = data["hardware_mapping"]

    content = f"""/**
 * @file Config.h
 * @brief AUTO-GENERATED FILE from project_config.json. DO NOT EDIT MANUALLY.
 * @date Generated by Tools/generate_config.py
 */

#pragma once

namespace Config {{

    namespace Plant {{
        constexpr float MASS_KG = {phy['mass_kg']};
        constexpr float GRAVITY = {phy['gravity_mss']};
        constexpr float EQUILIBRIUM_DIST_M = {phy['equilibrium_distance_m']};
        constexpr float COIL_RESISTANCE = {phy['coil_resistance_ohm']};
        constexpr float COIL_INDUCTANCE = {phy['coil_inductance_henry']};
    }}

    namespace Control {{
        constexpr float LOOP_FREQ_HZ = {ctrl['loop_frequency_hz']};
        constexpr float LOOP_PERIOD_S = 1.0f / {ctrl['loop_frequency_hz']};
        constexpr float TARGET_DIST_M = Plant::EQUILIBRIUM_DIST_M;
        
        namespace PID {{
            constexpr float KP = {ctrl['pid_gains']['kp']};
            constexpr float KI = {ctrl['pid_gains']['ki']};
            constexpr float KD = {ctrl['pid_gains']['kd']};
        }}
    }}

    namespace Hardware {{
        constexpr int PIN_HALL = {hw['pins']['hall_sensor_pin']};
        constexpr int PIN_PWM = {hw['pins']['pwm_coil_pin']};
        
        constexpr int ADC_BITS = {hw['adc_settings']['resolution_bits']};
        constexpr float ADC_REF_V = {hw['adc_settings']['reference_voltage_v']};
        constexpr float HALL_OFFSET_V = {hw['adc_settings']['sensor_zero_offset_v']};
        
        constexpr int PWM_FREQ = {hw['pwm_settings']['frequency_hz']};
        constexpr int PWM_BITS = {hw['pwm_settings']['resolution_bits']};
    }}
}}
"""
    os.makedirs(os.path.dirname(CPP_PATH), exist_ok=True)
    with open(CPP_PATH, 'w') as f:
        f.write(content)


def generate_matlab_script(data):
    print(f"Generating MATLAB Script: {MATLAB_PATH}")
    
    phy = data["physical_plant"]
    geo = phy["coil_geometry"] # Nuova sezione
    ctrl = data["control_system"]

    content = f"""% AUTO-GENERATED FILE from project_config.json
% Run this script to load parameters into the workspace

%% Physical Plant (Lumped)
mass = {phy['mass_kg']};
g = {phy['gravity_mss']};
x_eq = {phy['equilibrium_distance_m']};
R_coil = {phy['coil_resistance_ohm']};
L_coil = {phy['coil_inductance_henry']};
K_mag_approx = {phy['magnetic_constant_K']};
core_amp_factor = {phy['core_amplification_factor']};

%% Magnetic Properties
m_mag_val = {phy['magnet_dipole_moment_Am2']}; % Magnetic Dipole Moment [A*m^2]

%% Coil Geometry (For Advanced Modeling)
geom_R1 = {geo['inner_radius_m']};
geom_R2 = {geo['outer_radius_m']};
geom_L = {geo['length_m']};
geom_N = {geo['estimated_turns']};

%% Control System
Ts = 1 / {ctrl['loop_frequency_hz']}; % Sampling Time
Kp = {ctrl['pid_gains']['kp']};
Ki = {ctrl['pid_gains']['ki']};
Kd = {ctrl['pid_gains']['kd']};

disp('Aether-Lock Parameters Loaded Successfully');
"""
    os.makedirs(os.path.dirname(MATLAB_PATH), exist_ok=True)
    with open(MATLAB_PATH, 'w') as f:
        f.write(content)

def generate_markdown_doc(data):
    print(f"Generating Documentation: {DOCS_PATH}")
    
    phy = data["physical_plant"]
    ctrl = data["control_system"]
    
    content = f"""# System Parameters

> **Note:** This file is auto-generated from `project_config.json`. Do not edit manually.

## Physical Plant
| Parameter | Value | Unit | Description |
| :--- | :--- | :--- | :--- |
| Mass | `{phy['mass_kg']}` | kg | Mass of the Angel |
| Gravity | `{phy['gravity_mss']}` | m/s^2 | Gravitational acceleration |
| Equilibrium Distance | `{phy['equilibrium_distance_m']}` | m | Target air gap |
| Coil Resistance | `{phy['coil_resistance_ohm']}` | Ohm | Electromagnet DC resistance |
| Coil Inductance | `{phy['coil_inductance_henry']}` | Henry | Electromagnet inductance |
| Dipole Moment | `{phy['magnet_dipole_moment_Am2']}` | A·m² | Magnetic Moment (Calculated) |

## Control Settings
| Parameter | Value | Unit | Description |
| :--- | :--- | :--- | :--- |
| Loop Frequency | `{ctrl['loop_frequency_hz']}` | Hz | PID execution rate |
| Kp | `{ctrl['pid_gains']['kp']}` | - | Proportional Gain |
| Ki | `{ctrl['pid_gains']['ki']}` | - | Integral Gain |
| Kd | `{ctrl['pid_gains']['kd']}` | - | Derivative Gain |
"""
    os.makedirs(os.path.dirname(DOCS_PATH), exist_ok=True)
    with open(DOCS_PATH, 'w') as f:
        f.write(content)

if __name__ == "__main__":
    try:
        data = load_config()
        generate_cpp_header(data)
        generate_matlab_script(data)
        generate_markdown_doc(data)
        print("\nAll configuration files generated successfully!")
    except FileNotFoundError:
        print("Error: project_config.json not found in the project root.")
    except Exception as e:
        print(f"Error: {e}")
