/**
 * @file ThermalGuard.h
 * @brief Virtual sensor for estimating coil temperature and preventing overheating.
 * 
 * This class implements a first-order thermal model (Energy Balance) to estimate
 * the temperature of the electromagnet coil without a physical sensor.
 * It acts as a safety guard, triggering a shutdown signal if limits are exceeded.
 */

#ifndef THERMAL_GUARD_H
#define THERMAL_GUARD_H

class ThermalGuard {
private:
    /** 
     * @brief Current estimated temperature of the coil in degrees Celsius. 
     * Initialized to ambient temperature at startup.
     */
    float _current_temp;

public:
    /**
     * @brief Constructor. Initializes the thermal model.
     */
    ThermalGuard();

    /**
     * @brief Updates the thermal model based on current power usage.
     * 
     * This method must be called inside the main control loop (e.g., at 5kHz).
     * It calculates the heat generated by the current PWM duty cycle and 
     * subtracts the heat dissipated into the environment.
     * 
     * @param pwm_duty The current duty cycle applied to the coil (range 0.0 to 1.0).
     * @return true if temperature is within safe limits.
     * @return false if temperature exceeds MAX_TEMP_C (Overheating detected).
     */
    bool update(float pwm_duty);

    /**
     * @brief Gets the current estimated temperature.
     * 
     * @return float Temperature in degrees Celsius.
     */
    float getTemperature() const;

    /**
     * @brief Resets the thermal model.
     * 
     * Should be called when the system is reset or when we can assume 
     * the coil has cooled down to ambient temperature.
     */
    void reset();
};

#endif // THERMAL_GUARD_H