; --- GLOBAL SETTINGS ---
[platformio]
default_envs = esp32dev

; --- ESP32 STANDARD ENVIRONMENT ---
[env:esp32dev]
platform = espressif32
; Usiamo la definizione generica per ESP32 Standard
board = esp32dev
framework = arduino

; Hardware Configuration
; Rimosse le flag USB S2 perché il tuo chip usa il CP2102
build_flags = 
    -I include

; Serial Monitor & Upload Settings
monitor_speed = 115200
monitor_filters = time, colorize
upload_speed = 921600
; upload_port = COM3  ; Decommenta se serve forzare la porta

; --- SOURCE FILTER (Select One) ---

; MODE A: FLIGHT (Main PID Firmware)
; build_src_filter = +<*> -<HardwareTest.cpp> -<test_simulation.cpp>

; MODE B: HARDWARE TEST (Calibration & Check)
build_src_filter = +<HardwareTest.cpp> -<main.cpp> -<test_simulation.cpp>


; --- PC SIMULATION (Optional) ---
[env:native]
platform = native
test_framework = unity
lib_deps = Aether_Control
build_flags = -I include -std=c++11
build_src_filter = +<../test/test_simulation.cpp> -<src/*>