[env:esp32-s2-devkit]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino

; --- 1. USB S2 CONFIGURATION ---
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I include

; --- 2. SERIAL SPEED ---
monitor_speed = 115200
monitor_filters = time, colorize

; --- 3. NATIVE TEST ENVIRONMENT (PC) ---
[env:native]
platform = native
test_framework = unity
lib_deps = 
    Aether_Control
build_flags = 
    -I include 
    -std=c++11