; --- GLOBAL CONFIGURATION ---
[platformio]
; This line says: "When I click Build, compile ONLY for ESP32"
; (So it ignores Native and avoids errors)
default_envs = esp32-s2-devkit

; --- ESP32 ENVIRONMENT (Real Hardware) ---
[env:esp32-s2-devkit]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino

; USB Configuration & Include
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I include

; Serial Speed
monitor_speed = 115200
monitor_filters = time, colorize

; --- MODE SELECTOR ---
; Uncomment the line you need:

; MODE A: FLIGHT (PID Active)
; build_src_filter = +<*> -<HardwareTest.cpp> -<test_simulation.cpp>

; MODE B: HARDWARE TEST (Calibration)
build_src_filter = +<HardwareTest.cpp> -<main.cpp> -<test_simulation.cpp>


; --- NATIVE ENVIRONMENT (PC Simulation) ---
; Note: Requires MinGW/GCC installed on Windows
[env:native]
platform = native
test_framework = unity
lib_deps = 
    Aether_Control
build_flags = 
    -I include 
    -std=c++11
; Filter to compile only the simulation and not the Arduino code
build_src_filter = +<../test/test_simulation.cpp> -<src/*>